# fly.toml app configuration file generated for nats-aerl-cloud on 2023-08-10T13:45:18+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nats-aerl-cloud"
primary_region = "syd"

[build]

[[mounts]]
  source = "jetstream"
  destination = "/data"

[checks]
  [checks.health]
    port = 8222
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "GET"
    path = "/healthz"

[metrics]
  port = 7777
  path = "/metrics"
