app = "functions-aerl-cloud"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "syd"

[env]

[experimental]
    auto_rollback = true

[[services]]
  internal_port = 9000
  processes = ["app"]
  protocol = "tcp"

  [[services.http_checks]]
    grace_period = "5s"
    interval = "15s"
    method = "get"
    path = "/_internal/health"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    tls_skip_verify = true

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
