# fly.toml app configuration file generated for supabase-metrics-proxy on 2023-06-16T16:38:30+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "supabase-metrics-proxy"
primary_region = "syd"

[http_service]
    internal_port = 8080
    force_https = true
    min_machines_running = 1

[metrics]
    port = 8080
    path = "/metrics"
