{
 "title": "Earth Guard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Resistance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "canbus_aerl_earthguard_pv1_resistance_negative"
    },
    {
     "expr": "canbus_aerl_earthguard_pv1_resistance_positive"
    },
    {
     "expr": "canbus_aerl_earthguard_pv2_resistance_negative"
    },
    {
     "expr": "canbus_aerl_earthguard_pv2_resistance_positive"
    }
   ]
  },
  {
   "title": "Error Flags",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\"canbus_aerl_earthguard_flags_.*\"}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "canbus_aerl_earthguard_voltage_pv1"
    },
    {
     "expr": "canbus_aerl_earthguard_voltage_pv2"
    },
    {
     "expr": "canbus_pv_measurement_voltage{hub=\"23000004\"}"
    }
   ]
  }
 ]
}