{
 "title": "SRX",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Connected Device",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "last_over_time(canbus_information_serial_number[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "canbus_pv_measurement_current", "legendFormat": "__auto" },
    {
     "expr": "canbus_output_measurement_current",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "canbus_output_measurement_voltage * canbus_output_measurement_current",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "canbus_pv_power_battery_temperature_batter_temperature",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "canbus_pv_measurement_voltage", "legendFormat": "__auto" },
    {
     "expr": "canbus_output_measurement_voltage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Flags",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "{__name__=~\"canbus_flags_.+\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}