apiVersion: 1

datasources:

  - name: Fly Metrics
    type: prometheus
    url: https://api.fly.io/prometheus/aerl
    prometheusType: Prometheus
    jsonData:
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Bearer ${FLY_API_TOKEN}'

  - name: Mimir
    type: prometheus
    prometheusType: Mimir
    url: http://mimir-aerl-cloud.internal:8080/prometheus
    jsonData:
      httpHeaderName1: 'X-Scope-OrgID'
    secureJsonData:
      httpHeaderValue1: 'aMAa|anonymous|el5a'

  - name: Mimir Redis
    type: redis-datasource
    url: redis://fly-mimir-aerl-cloud.upstash.io:6379
    jsonData:
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    secureJsonData:
      password: $MIMIR_REDIS_PASSWORD

  - name: Loki
    type: loki
    url: http://loki-aerl-cloud.internal:3100
