target: all

multitenancy_enabled: true

tenant_federation:
  # allow cross tenant queries
  enabled: true

usage_stats:
  # don't report usage statistics (just in case)
  enabled: false

common:
  storage:
    backend: s3
    s3:
      region: apac
      endpoint: ${S3_ENDPOINT}
      bucket_name: ${S3_BUCKET_NAME}
      access_key_id: ${S3_ACCESS_KEY_ID}
      secret_access_key: ${S3_SECRET_ACCESS_KEY}

server:
  # listen to all IPv6 addresses
  grpc_listen_address: '[::]'

limits:
  out_of_order_time_window: 8h

frontend:
  # should be multiple of 24h to align with blocks.
  split_queries_by_interval: 24h
  align_queries_with_step: true
  query_stats_enabled: false
  log_queries_longer_than: 3s
  address: "${FLY_ALLOC_ID}.vm.${FLY_APP_NAME}.internal"
  cache_results: true
  results_cache:
    compression: "snappy"
    backend: redis
    redis:
      endpoint: ${REDIS_HOST}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

querier:
  timeout: 30s

blocks_storage:
  storage_prefix: blocks
  tsdb:
    dir: /data/ingester
  bucket_store:
    sync_dir: /data/tsdb-sync
    index_cache:
      backend: redis
      redis:
        endpoint: ${REDIS_HOST}
        username: ${REDIS_USERNAME}
        password: ${REDIS_PASSWORD}
    chunks_cache:
      backend: redis
      redis:
        endpoint: ${REDIS_HOST}
        username: ${REDIS_USERNAME}
        password: ${REDIS_PASSWORD}
        # Max size of 10MB set by Upstash/Fly
        # https://fly.io/docs/reference/redis/#pricing
        max_item_size: 10485760

    metadata_cache:
      backend: redis
      redis:
        endpoint: ${REDIS_HOST}
        username: ${REDIS_USERNAME}
        password: ${REDIS_PASSWORD}

distributor:
  ring:
    kvstore:
      store: consul
      prefix: ${CONSUL_PREFIX}
      consul:
        host: ${CONSUL_URL}
        acl_token: ${CONSUL_TOKEN}
    instance_addr: "${FLY_ALLOC_ID}.vm.${FLY_APP_NAME}.internal"

ingester:
  ring:
    kvstore:
      store: consul
      prefix: ${CONSUL_PREFIX}
      consul:
        host: ${CONSUL_URL}
        acl_token: ${CONSUL_TOKEN}
    instance_availability_zone: ${FLY_REGION}
    instance_addr: "${FLY_ALLOC_ID}.vm.${FLY_APP_NAME}.internal"

compactor:
  sharding_ring:
    kvstore:
      store: consul
      prefix: ${CONSUL_PREFIX}
      consul:
        host: ${CONSUL_URL}
        acl_token: ${CONSUL_TOKEN}
    instance_addr: "${FLY_ALLOC_ID}.vm.${FLY_APP_NAME}.internal"

store_gateway:
  sharding_ring:
    kvstore:
      store: consul
      prefix: ${CONSUL_PREFIX}
      consul:
        host: ${CONSUL_URL}
        acl_token: ${CONSUL_TOKEN}
    instance_availability_zone: ${FLY_REGION}
    instance_addr: "${FLY_ALLOC_ID}.vm.${FLY_APP_NAME}.internal"

ruler:
  alertmanager_url: "https://sb.aerl.cloud/functions/v1/alertmanager"
  alertmanager_client:
    basic_auth_username: ${ALERTMANAGER_USERNAME}
    basic_auth_password: ${ALERTMANAGER_PASSWORD}
  tenant_federation:
    enabled: true
  ring:
    kvstore:
      store: consul
      prefix: ${CONSUL_PREFIX}
      consul:
        host: ${CONSUL_URL}
        acl_token: ${CONSUL_TOKEN}
    instance_addr: "${FLY_ALLOC_ID}.vm.${FLY_APP_NAME}.internal"
